project:
  type: website

website:
  title: "Dynamic Risk Prediction"
  navbar:
    logo: ./img/logo.png
    left:
      - href: lectures/index.qmd
        text: Introduction
      - href: lectures/data_management.qmd
        text: Data
      - href: lectures/modelling.qmd
        text: Modelling
      - href: lectures/implementation.qmd
        text: Implementation
    right: 
      - icon: github
        href: https://github.com/hds-sandbox
        aria-label: GitHub
      - icon: linkedin
        href: https://www.linkedin.com/company/ucph-heads/
        aria-label: LinkedIn
      

format:
  html:
    theme: 
      light: [materia, css/materialight.scss]
      dark: darkly
    toc: true
    code-fold: true
#    include-in-header:
#      - file: "resources/bioschema.html"
